package Porrinha;


/**
* Porrinha/namesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Domingo, 25 de Junho de 2017 22h29min39s GFT
*/

public final class namesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public namesHolder ()
  {
  }

  public namesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Porrinha.namesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Porrinha.namesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Porrinha.namesHelper.type ();
  }

}
