package Porrinha;


/**
* Porrinha/ServerPorrinha.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Domingo, 25 de Junho de 2017 22h29min39s GFT
*/

public interface ServerPorrinha extends ServerPorrinhaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerPorrinha
