package Porrinha;

/**
* Porrinha/ClientPorrinhaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quarta-feira, 21 de Junho de 2017 11h32min43s BRT
*/

public final class ClientPorrinhaHolder implements org.omg.CORBA.portable.Streamable
{
  public Porrinha.ClientPorrinha value = null;

  public ClientPorrinhaHolder ()
  {
  }

  public ClientPorrinhaHolder (Porrinha.ClientPorrinha initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Porrinha.ClientPorrinhaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Porrinha.ClientPorrinhaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Porrinha.ClientPorrinhaHelper.type ();
  }

}
