package Porrinha;


/**
* Porrinha/ClientPorrinha.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quinta-feira, 22 de Junho de 2017 10h29min13s BRT
*/

public interface ClientPorrinha extends ClientPorrinhaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientPorrinha
