package Porrinha;


/**
* Porrinha/ClientPorrinhaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quarta-feira, 14 de Junho de 2017 23h13min21s GFT
*/

public interface ClientPorrinhaOperations 
{
  void tellNumberOfPicks ();
  void tellResultGuess ();
  void roundFinished (int result, int maxSum);
} // interface ClientPorrinhaOperations
