package Porrinha;


/**
* Porrinha/ClientPorrinhaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quinta-feira, 22 de Junho de 2017 10h29min13s BRT
*/

public interface ClientPorrinhaOperations 
{
  void tellNumberOfPicks ();
  void tellResultGuess (int maxSum);
  void roundFinished (int result, int maxSum);
  void waitForStart ();
} // interface ClientPorrinhaOperations
