package Porrinha;


/**
* Porrinha/ClientPorrinha.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quarta-feira, 21 de Junho de 2017 11h32min43s BRT
*/

public interface ClientPorrinha extends ClientPorrinhaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientPorrinha
