package Porrinha;


/**
* Porrinha/ClientPorrinhaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quinta-feira, 22 de Junho de 2017 10h29min13s BRT
*/

abstract public class ClientPorrinhaHelper
{
  private static String  _id = "IDL:Porrinha/ClientPorrinha:1.0";

  public static void insert (org.omg.CORBA.Any a, Porrinha.ClientPorrinha that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Porrinha.ClientPorrinha extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Porrinha.ClientPorrinhaHelper.id (), "ClientPorrinha");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Porrinha.ClientPorrinha read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientPorrinhaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Porrinha.ClientPorrinha value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Porrinha.ClientPorrinha narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Porrinha.ClientPorrinha)
      return (Porrinha.ClientPorrinha)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Porrinha._ClientPorrinhaStub stub = new Porrinha._ClientPorrinhaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Porrinha.ClientPorrinha unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Porrinha.ClientPorrinha)
      return (Porrinha.ClientPorrinha)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Porrinha._ClientPorrinhaStub stub = new Porrinha._ClientPorrinhaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
