package Porrinha;


/**
* Porrinha/ClientPorrinhaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quarta-feira, 21 de Junho de 2017 11h32min43s BRT
*/

public interface ClientPorrinhaOperations 
{
  void tellNumberOfPicks ();
  void tellResultGuess ();
  void roundFinished (int result, int maxSum);
  void waitForStart ();
} // interface ClientPorrinhaOperations
