package Porrinha;

/**
* Porrinha/ServerPorrinhaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Quarta-feira, 14 de Junho de 2017 23h13min21s GFT
*/

public final class ServerPorrinhaHolder implements org.omg.CORBA.portable.Streamable
{
  public Porrinha.ServerPorrinha value = null;

  public ServerPorrinhaHolder ()
  {
  }

  public ServerPorrinhaHolder (Porrinha.ServerPorrinha initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Porrinha.ServerPorrinhaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Porrinha.ServerPorrinhaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Porrinha.ServerPorrinhaHelper.type ();
  }

}
