module Porrinha{
	interface ServerPorrinha {
		void registerClient(in string clientName);
		void putNumberOfPicks(in string clientName, in long picks);
		void putResultGuess(in string clientName, in long guess);
	};

	typedef sequence<string> names;
	interface ClientPorrinha {
		void tellPlayersNames(in names players, in long length);
		void tellNumberOfPicks();
		void tellResultGuess(in long maxSum);
		void roundFinished(in long result, in long maxSum, in names playersPicks, in names winners);
		void waitForStart();
	};
};
